"""Create session table

Revision ID: 29a7bb38b7a5
Revises: 7212c468122a
Create Date: 2022-05-10 12:31:05.097574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29a7bb38b7a5'
down_revision = '7212c468122a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.add_column('user', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_updated')
    op.drop_column('user', 'time_created')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
