"""Updating user tabel remove nullable'

Revision ID: 56cabb51a54b
Revises: 012af9d23652
Create Date: 2022-05-12 20:45:18.429231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cabb51a54b'
down_revision = '012af9d23652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
