"""Updating user and session time updated 3

Revision ID: 710e465e30ef
Revises: b7713a43a812
Create Date: 2022-05-12 21:05:39.074368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710e465e30ef'
down_revision = 'b7713a43a812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
