"""Update user database 4

Revision ID: 7212c468122a
Revises: 98a4624d0765
Create Date: 2022-05-09 15:34:49.128976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7212c468122a'
down_revision = '98a4624d0765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
