"""Updating user tabel add nullable again

Revision ID: 981d62201938
Revises: 56cabb51a54b
Create Date: 2022-05-12 20:48:48.061056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981d62201938'
down_revision = '56cabb51a54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
