"""Update user database 3

Revision ID: 98a4624d0765
Revises: d91f1309a83b
Create Date: 2022-05-09 15:32:18.739590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a4624d0765'
down_revision = 'd91f1309a83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
