"""Updating user and session time updated

Revision ID: 9ae3b4335526
Revises: 981d62201938
Create Date: 2022-05-12 20:54:37.451678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae3b4335526'
down_revision = '981d62201938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
