"""Updating user table with roles

Revision ID: a35efde0ee5c
Revises: 9f1f4821bca3
Create Date: 2022-05-16 11:18:08.360651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35efde0ee5c'
down_revision = '9f1f4821bca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute("""
            CREATE TYPE userrole AS ENUM ('ADMIN', 'REGULAR');
        """)
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'REGULAR', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
