"""Updating user and session time updated 2

Revision ID: b7713a43a812
Revises: d6c34cb6a33e
Create Date: 2022-05-12 21:02:17.596207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7713a43a812'
down_revision = 'd6c34cb6a33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
