"""Updating user table with roles with default

Revision ID: bcae2866a984
Revises: a35efde0ee5c
Create Date: 2022-05-16 11:36:49.261460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcae2866a984'
down_revision = 'a35efde0ee5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'REGULAR', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'REGULAR', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
