"""Updating user table with cascade delete to sessions

Revision ID: c4e31f9c5a53
Revises: bcae2866a984
Create Date: 2022-05-16 20:26:18.891344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e31f9c5a53'
down_revision = 'bcae2866a984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
