"""Updating user table with fullname and getter for photo

Revision ID: d61dec23aab9
Revises: c4e31f9c5a53
Create Date: 2022-05-20 19:19:13.653621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61dec23aab9'
down_revision = 'c4e31f9c5a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(), nullable=False))
    op.drop_column('user', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
