"""Updating user and session time updated

Revision ID: d6c34cb6a33e
Revises: 9ae3b4335526
Create Date: 2022-05-12 21:02:07.035861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c34cb6a33e'
down_revision = '9ae3b4335526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
