"""Updating user and session time updated 4

Revision ID: ec85648a1114
Revises: 710e465e30ef
Create Date: 2022-05-12 21:20:41.332116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec85648a1114'
down_revision = '710e465e30ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
