"""Updating user table photo

Revision ID: fcd283faf216
Revises: d61dec23aab9
Create Date: 2022-05-20 19:43:05.736469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd283faf216'
down_revision = 'd61dec23aab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_photo', sa.String(), nullable=False, server_default="default.png"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_photo')
    # ### end Alembic commands ###
